# Generated by Django 4.1.4 on 2023-11-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=20)),
                ('Image', models.ImageField(default='null.jpg', upload_to='image')),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
    ]
