# Generated by Django 4.1.4 on 2023-12-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='null.jpg', upload_to='images'),
        ),
    ]
