# Generated by Django 4.1.4 on 2023-12-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Category',
            new_name='category',
        ),
    ]
