# Generated by Django 4.1.4 on 2023-12-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_rename_category_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Services',
            new_name='Location',
        ),
    ]
