# Generated by Django 4.1.4 on 2023-12-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_rename_services_branch_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Image',
            new_name='Img',
        ),
    ]
