# Generated by Django 4.1.4 on 2023-12-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0007_rename_image_branch_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=20)),
                ('Pass_word', models.CharField(max_length=4)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Email', models.EmailField(default='null@gmail.com', max_length=254)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Time', models.TimeField()),
                ('Servi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.service')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.register')),
            ],
        ),
    ]
