# Generated by Django 4.1.4 on 2023-12-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
