# Generated by Django 4.1.4 on 2023-12-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0007_rename_image_branch_img'),
        ('Userapp', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Time', models.TimeField()),
                ('Servi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.service')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.register')),
            ],
        ),
    ]
