# Generated by Django 4.1.4 on 2023-12-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_rename_servi_book_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
